Task: 03-date-tasks
verenichyi/js-internship pull request #3
Opened 2023-02-06 19:51 UTC by verenichyi

2023-02-09 09:30 UTC, echonok requested changes

2023-02-09 09:30 UTC, echonok commented on js/practice/task/03-date-tasks.js
> +	return Date.parse(value);
It does fit tests, but the type of the result is not Date. Please, function must return Date type

2023-02-09 09:30 UTC, echonok commented on js/practice/task/03-date-tasks.js
> +	return Date.parse(value);
Same here

2023-02-09 09:30 UTC, echonok commented on js/practice/task/03-date-tasks.js
> +	return ((year % 4 === 0) && (year % 100 !== 0)) || (year % 400 === 0);
Very good

2023-02-09 15:02 UTC, verenichyi commented on js/practice/task/03-date-tasks.js
> +	return Date.parse(value);
Fixed

2023-02-09 15:03 UTC, verenichyi commented on js/practice/task/03-date-tasks.js
> +	return Date.parse(value);
Fixed

2023-02-09 15:13 UTC, echonok commented on js/practice/task/03-date-tasks.js
> +	return Date.parse(value);
What did you fix? :D

2023-02-10 10:02 UTC, verenichyi commented on js/practice/task/03-date-tasks.js
> +	return Date.parse(value);
Oh, I'm so sorry!
Forgot to push the commit.

2023-02-15 11:12 UTC, echonok approved these changes

2023-02-15 14:14 UTC, merged