Task: 04-arrays-tasks
verenichyi/js-internship pull request #4
Opened 2023-02-07 12:48 UTC by verenichyi

Implement `findElement`, `generateOdds`, `doubleArray`, `getArrayOfPositives`, `getArrayOfStrings`, `removeFalsyValues`, `getUpperCaseStrings`, `getStringsLength`, `insertItem`, `getHead`, `getTail`, `toCsvText`, `toArrayOfSquares`, `getMovingSum`, `getSecondItems`, `propagateItemsByPositionIndex`, `get3TopItems`, `getPositivesCount`, `sortDigitNamesByNumericOrder`, `getItemsSum`, `getFalsyValuesCount`, `findAllOccurences`, `toStringList`, `sortCitiesArray`, `getIdentityMatrix`, `getIntervalArray`, `distinct`, `group`, `selectMany`, `getElementByIndexes`, `swapHeadAndTail` funcs

2023-02-09 09:28 UTC, echonok requested changes

2023-02-09 09:28 UTC, echonok commented on js/practice/task/04-arrays-tasks.js
> +	return arr.sort((a, b) => map[a] - map[b]);
I would only add toLowerCase

2023-02-09 09:28 UTC, echonok commented on js/practice/task/04-arrays-tasks.js
> +	return arr.map((x, i) => (i < mid) ? arr[mid + i] || x : arr[i - mid]);
Look, your solution does the trick but consumes too much effort. We don't deen to loop through an array. Why don't use `slice`?

2023-02-09 15:10 UTC, verenichyi commented on js/practice/task/04-arrays-tasks.js
> +	return arr.sort((a, b) => map[a] - map[b]);
Refactored

2023-02-09 15:43 UTC, verenichyi commented on js/practice/task/04-arrays-tasks.js
> +	return arr.map((x, i) => (i < mid) ? arr[mid + i] || x : arr[i - mid]);
Refactored

2023-02-10 08:24 UTC, echonok approved these changes

2023-02-10 09:57 UTC, merged